cache:
  paths:
    - /root/.m2/repository

before_script:
  - docker login -u="$DOCKER_HUB_USER" -p="$DOCKER_HUB_PASSWORD" docker.io

stages:
#  - build
#  - test
  - deploy

#build:
#  stage: build
#  image: maven:3.6.3-openjdk-15
#  script:
#    - mvn package -B
#  tags:
#    - docker
#
#test:
#  stage: test
#  image: maven:3.6.3-openjdk-15
#  script:
#    - mvn test
#  tags:
#    - docker

deploy_prod:
  stage: deploy
  image: docker:dind
  script:
    - docker-compose build
    - docker tag spring-boot-gitlab-ci-heroku-build_app $DOCKER_HUB_USER/spring-boot-gitlab-ci-heroku-build_app:latest_prod
    - docker push $DOCKER_HUB_USER/spring-boot-gitlab-ci-heroku-build_app:latest_prod
  environment:
    name: prod
#    url: https://spring-boot-gitlab-ci-prod.herokuapp.com/
#  when: manual
  only:
    - master
  tags:
    - docker

#deploy_stage:
#  stage: deploy
#  image: ruby:latest
#  script:
#    - gem install dpl
#    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY
#  environment:
#    name: stage
#    url: https://spring-boot-gitlab-ci-stage.herokuapp.com/
#  only:
#    - master
#  tags:
#    - docker
