cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-15
  script:
    - mvn clean install -DskipTests=true
  tags:
    - docker

test:
  stage: test
  image: maven:3.6.3-openjdk-15
  script:
    - mvn test
  tags:
    - docker

package:
  stage: package
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.12-dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker tag spring-boot-gitlab-ci-heroku-build_app registry.gitlab.com/krizsan.balazs/spring-boot-gitlab-ci-heroku-build:latest
  only:
    - master
  tags:
    - docker

deploy:
  stage: deploy
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.12-dind
  script:
    - docker push registry.gitlab.com/krizsan.balazs/spring-boot-gitlab-ci-heroku-build:latest
  only:
    - master
  tags:
    - docker
