cache:
  paths:
    - /root/.m2/repository

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

stages:
  - build
#  - test
#  - deploy

#build:
#  stage: build
#  image: maven:3.6.3-openjdk-15
#  script:
#    - mvn package -B
#  tags:
#    - docker
#
#test:
#  stage: test
#  image: maven:3.6.3-openjdk-15
#  script:
#    - mvn test
#  tags:
#    - docker

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker-compose build
    - docker tag spring-boot-gitlab-ci-heroku-build_app registry.gitlab.com/krizsan.balazs/spring-boot-gitlab-ci-heroku-build:latest
    - push registry.gitlab.com/krizsan.balazs/spring-boot-gitlab-ci-heroku-build:latest
  environment:
    name: prod
#    url: https://spring-boot-gitlab-ci-prod.herokuapp.com/
#  when: manual
  only:
    - master
  tags:
    - docker

#deploy_stage:
#  stage: deploy
#  image: ruby:latest
#  script:
#    - gem install dpl
#    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY
#  environment:
#    name: stage
#    url: https://spring-boot-gitlab-ci-stage.herokuapp.com/
#  only:
#    - master
#  tags:
#    - docker
