version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8182
    environment:
      - SERVER_PORT=8182
    depends_on:
      - database
#    volumes:
#      - m2-repo:/root/.m2/repository

  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=rainbow_database

#volumes:
#  m2-repo:
